version: '3.9'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:80"
    environment:
      TIINGO_API_KEY: "${TIINGO_API_KEY}"

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  test:
    build:
      context: .
      dockerfile: ./backend.Tests/Dockerfile.test
    depends_on:
      - backend
    profiles: ["test"]